# Generated by Django 5.2.6 on 2025-09-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_telephone_activation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="statut",
            field=models.BooleanField(default=False),
        ),
    ]
