# Generated by Django 5.2.6 on 2025-09-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_activation_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="image",
            field=models.ImageField(blank=True, upload_to="produits/"),
        ),
    ]
