# Generated by Django 5.2.6 on 2025-09-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_produit_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="quantite",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
