# Generated by Django 5.2.6 on 2025-09-06 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "identifiant",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenue", models.TextField()),
                ("numero", models.CharField(editable=False, max_length=8, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("statut", models.BooleanField(default=True)),
                (
                    "mode_livraison",
                    models.CharField(
                        choices=[
                            ("Domicile", "Domicile"),
                            ("Point relais", "Point relais"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("Mobile Money", "Mobile Money"),
                            ("carte", "Carte bancaire"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
